### ISSUE TITLE
Drall 2.x and 3.x cannot catch some Drush output

### ISSUE THREAD

**Issue by jigarius** [jigarius/drall#71]
## The problem

- Execute `drall ex drush cr`
- The command runs successfully, but Drall cannot display the `[success] Cache rebuild complete.` message generated by Drush.

**Comment by dasginganinja** [comment]
This is likely related to the fact that drush writes to stderr. You would need to catch both the standard out and the standard error. :)

**Comment by dasginganinja** [comment]
I took a look into this today. 

It appears you are using the amp library to run the processes (versus Symfony).

Amp separates the output streams into stdout and stderr.  
https://github.com/amphp/process/blob/2.x/src/Process.php#L218

Symfony, on the other hand, provides you with a stream and you can get the type of data.
https://symfony.com/doc/current/components/process.html#usage

In your example, you create an amp process.  
https://github.com/jigarius/drall/blob/3.x/src/Commands/ExecCommand.php#L156

Perhaps the amp library should be able to provide a stream of both like Symfony does or maybe there is a better way of muxing the data together? 

It would be weird to print stdout then stderr since they are timed data and could interweave.
🤔

**Comment by jigarius** [comment]
Thanks for the insight. I will do some research in the first week of May and the worst of cases, I'll request AMP maintainers to help.

**Comment by jigarius** [comment]
I was reading a bit about this and it turns out that Drush writes all log messages to `STDERR` by design. I think the next step will be to find a way to force all the output into a single stream when running the commands. Maybe we can do something like append `2>&1` to the commands. I'll give that a try and some tests to make sure we get messages like:

    [success] Cache rebuild successful.

**Reference:** https://github.com/drush-ops/drush/issues/707

**Comment by jigarius** [comment]
I've made a commit that fixes this issue and catches STDERR output correctly. However, there seems to be an irrelevant issue where `Drush` has an incompatible method declaration. I'll solve that dependency issue first and then continue on fixing this.
